[package]
name = "rust_chat_app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.5", features = ["derive"] } 